// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/turso-migrations",
  },
  datasource: {
    // Prisma Migrate cannot apply schema changes over libSQL's remote HTTP
    // transport. Generate migrations against this local SQLite shadow file,
    // then apply them to Turso with scripts/apply-turso-migrations.ts.
    url: process.env["LOCAL_DATABASE_URL"] ?? "file:./data/kult-prisma.db",
  },
});
